### ISSUE TITLE
Unable to start the fiware-pep-proxy server

### ISSUE THREAD

**Issue by albertinisg** [ging/fi-ware-pep-proxy#3]
Hi! 

I'm trying to deploy a secure environment for testing using the three security GEs (authzforce, IdM and fi-ware-pep-proxy).

With a clean installation of IdM, several organizations, applications and users are provided. I've tested to modify the roles and permissions against authzforce and the exchange of XACML's worked perfectly.

But now, trying to introduce the fi-ware-pep-proxy, I'm having issues with the authentication.

Here's the `config.js` file I've used:

<pre>
 var config = {};

config.pep_port = 10026;

// Set this var to undefined if you don't want the server to listen on HTTPS
//config.https = {
//    enabled: false,
//    cert_file: 'cert/cert.crt',
//    key_file: 'cert/key.key',
//    port: 443
//};

// Our IdM IP
config.account_host = '172.17.0.159';

// Our Keystone Settings. In this case Keystone and Horizon are at the same host
config.keystone_host = '172.17.0.159';
config.keystone_port = 5000;

// The host of the app to protect
config.app_host = '172.17.0.96';
config.app_port = '1026';

// The username and password we've used for registering the app (just for testing)
config.username = 'user0@test.com';
config.password = 'test';

// in seconds
config.chache_time = 300;

// if enabled PEP checks permissions with AuthZForce GE.
// only compatible with oauth2 tokens engine
config.azf = {
    enabled: true,
    host: '172.17.0.72',
    port: 8080,
    path: '/authzforce/domains/f7727b3b-0a04-11e5-9a3a-adc96088fc92/pdp'
};

// options: oauth2/keystone
config.tokens_engine = 'oauth2';

// 'client secret' of our registed app
config.magic_key = '82df536ff47...5beb9766';

module.exports = config;
</pre>

There, with this configuration file, I got the following message when running `sudo node server` :
<pre>
Starting PEP proxy in port 10026. Keystone authentication ...
Error in keystone communication {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
</pre>

I've checked Keystone logs and also the same error is there. Checking the API examples [here](http://docs.openstack.org/developer/keystone/api_curl_examples.html), I've tried to retrieve the token manually using the [Default scope](http://docs.openstack.org/developer/keystone/api_curl_examples.html#default-scope) and it worked perfectly. Then found that the request done for the fi-ware-pep-proxy at `lib/idm.js` is a [Domain Scoped](http://docs.openstack.org/developer/keystone/api_curl_examples.html#domain-scoped) request. 

So, at this point, I'm a bit lost. Is there any configuration I should add to my IdM? Any help would be appreciated!

**Comment by aalonsog** [comment]
Hi, 

it depends on where you have the user user0@test.com created... If it is in the default domain, it should work. 

BR

**Comment by albertinisg** [comment]
Yes, if I'm not wrong by default multi-domain is disabled, but also I've tested it and the user is located in the default domain (I've get the information using the Default Scope request):

<pre>
bitergia@af706c47bb48:~/fi-ware-pep-proxy$   curl -i \
>   -H "Content-Type: application/json" \
>   -d '
> { "auth": {
>     "identity": {
>       "methods": ["password"],
>       "password": {
>         "user": {
>           "name": "user0@test.com",
>           "domain": { "id": "default" },
>           "password": "test"
>         }
>       }
>     }
>   }
> }' \
>   http://172.17.0.159:5000/v3/auth/tokens ;
HTTP/1.1 201 Created
X-Subject-Token: 3461d8f05b0644ca862ae32a64ef16f1
...
</pre>

And there

<pre>
bitergia@af706c47bb48:~/fi-ware-pep-proxy$ curl -s   -H "X-Auth-Token: 3461d8f05b0644ca862ae32a64ef16f1"   http://172.17.0.159:5000/v3/domains | python -mjson.tool
{
    "domains": [
        {
            "description": "Owns users and tenants (i.e. projects) available on Identity API v2.",
            "enabled": true,
            "id": "default",
            "links": {
                "self": "http://172.17.0.159:5000/v3/domains/default"
            },
            "name": "Default"
        }
    ],
    "links": {
        "next": null,
        "previous": null,
        "self": "http://172.17.0.159:5000/v3/domains"
    }
}
</pre>

But, as I said below, the Domain Scoped one returns this one:

<pre>
bitergia@af706c47bb48:~/fi-ware-pep-proxy$ curl -i \
>   -H "Content-Type: application/json" \
>   -d '
> { "auth": {
>     "identity": {
>       "methods": ["password"],
>       "password": {
>         "user": {
>           "name": "user0@test.com",
>           "domain": { "id": "default" },
>           "password": "test"
>         }
>       }
>     },
>     "scope": {
>       "domain": {
>         "id": "default"
>       }
>     }
>   }
> }' \
>   http://172.17.0.159:5000/v3/auth/tokens ; echo
HTTP/1.1 401 Unauthorized
Www-Authenticate: Keystone uri="http://172.17.0.159:5000"
Vary: X-Auth-Token
Content-Type: application/json
Content-Length: 114
Date: Thu, 11 Jun 2015 16:54:13 GMT

{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
</pre>

**Comment by aalonsog** [comment]
It seems that your user has not any role in the default domain. 

Get a domain-scoped token (Note that you’re going to need a role-assignment on the domain first!):

**Comment by albertinisg** [comment]
Hi Álvaro!

You are completely right. I was misunderstanding the concept role-assignment, and adding roles to the user0 into the application and not domain. When checked I've found that the user didn't have any domain-roles assigned:

<pre>
{"links": {"self": "http://172.17.0.159:5000/v3/domains/default/users/user0/roles", "previous": null, "next": null}, "roles": []}
</pre>

So I've added it as a 'member', re-launched the PEP proxy and the authentication was successful :)

You can close the ticket.

Thanks for the support!
